# Generated by Django 3.2.15 on 2022-11-30 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        ('services_provider', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.ManyToManyField(related_name='appointment_meeting_type', to='services_provider.MeetingInformation'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_client', to='clients.clients'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_service_provider', to='services_provider.serviceprovider'),
        ),
    ]
