# Generated by Django 3.2.15 on 2022-11-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='additional_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_type',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.ManyToManyField(related_name='appointment_meeting_type', to='home.MeetingInformation'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='appointment_cost',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
