# Generated by Django 3.2.15 on 2022-11-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_appointment_cost_serviceprovider_appointment_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='speciality',
        ),
    ]
